_archive_deploys/deploy-pl-page/force-app/main/default/objects/Opportunity/fields/Property_Location__c.field-meta.xml
<CustomField>
    <fullName>Property_Location__c</fullName>
    <label>Property Location</label>
    <referenceTo>Property_Location__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

_archive_deploys/retrieve-listviews-2026-05-08/retrieved/unpackaged/objects/Property_Location__c.object
<CustomObject>
    <fields>
        <fullName>Active_Unit_Count__c</fullName>
        <label>Active Unit Count</label>
        <summaryFilterItems>
            <field>Property_Unit__c.Activated__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </summaryFilterItems>
        <summaryForeignKey>Property_Unit__c.Property_Location__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Property_Unit_Count__c</fullName>
        <label>Property Unit Count</label>
        <summaryForeignKey>Property_Unit__c.Property_Location__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Property Location</label>
    <nameField>
        <label>Property Location ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tracker-lwc/force-app/main/default/classes/PropertyLocationSummaryController.cls
public with sharing class PropertyLocationSummaryController {

    @AuraEnabled(cacheable=true)
    public static Summary getSummary(Id opportunityId) {
        Summary s = new Summary();
        if (opportunityId == null) {
            return s;
        }

        List<Opportunity> opps = [
            SELECT Property_Location__c,
                   Property_Location__r.Name,
                   Property_Location__r.Property_Unit_Count__c,
                   Property_Location__r.Active_Unit_Count__c
            FROM Opportunity
            WHERE Id = :opportunityId
            LIMIT 1
        ];
        if (opps.isEmpty() || opps[0].Property_Location__c == null) {
            return s;
        }

        Id plId = opps[0].Property_Location__c;
        s.plId = plId;
        s.plName = opps[0].Property_Location__r.Name;
        s.unitCount = opps[0].Property_Location__r.Property_Unit_Count__c;
        s.activeUnitCount = opps[0].Property_Location__r.Active_Unit_Count__c;
        s.oppCount = [
            SELECT COUNT()
            FROM Opportunity
            WHERE Property_Location__c = :plId
        ];
        return s;
    }

    public class Summary {
        @AuraEnabled public Id plId;
        @AuraEnabled public String plName;
        @AuraEnabled public Integer oppCount;
        @AuraEnabled public Decimal unitCount;
        @AuraEnabled public Decimal activeUnitCount;
    }
}